#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGPM.R.LinqHelper
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WGPM34")]
	public partial class DbAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertActivate(Activate instance);
    partial void UpdateActivate(Activate instance);
    partial void DeleteActivate(Activate instance);
    partial void InsertPushPlan(PushPlan instance);
    partial void UpdatePushPlan(PushPlan instance);
    partial void DeletePushPlan(PushPlan instance);
    partial void InsertPingInfo(PingInfo instance);
    partial void UpdatePingInfo(PingInfo instance);
    partial void DeletePingInfo(PingInfo instance);
    partial void InsertPushInfo(PushInfo instance);
    partial void UpdatePushInfo(PushInfo instance);
    partial void DeletePushInfo(PushInfo instance);
    #endregion
		
		public DbAppDataContext() : 
				base(global::WGPM.Properties.Settings.Default.WGPM34ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Activate> Activate
		{
			get
			{
				return this.GetTable<Activate>();
			}
		}
		
		public System.Data.Linq.Table<PushPlan> PushPlan
		{
			get
			{
				return this.GetTable<PushPlan>();
			}
		}
		
		public System.Data.Linq.Table<PingInfo> PingInfo
		{
			get
			{
				return this.GetTable<PingInfo>();
			}
		}
		
		public System.Data.Linq.Table<PushInfo> PushInfo
		{
			get
			{
				return this.GetTable<PushInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Activate")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Activate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<byte> _启动;
		
		private System.Nullable<byte> _退出;
		
		private System.Nullable<System.DateTime> _时间;
		
		private string _IP地址;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void On启动Changing(System.Nullable<byte> value);
    partial void On启动Changed();
    partial void On退出Changing(System.Nullable<byte> value);
    partial void On退出Changed();
    partial void On时间Changing(System.Nullable<System.DateTime> value);
    partial void On时间Changed();
    partial void OnIP地址Changing(string value);
    partial void OnIP地址Changed();
    #endregion
		
		public Activate()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_启动", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<byte> 启动
		{
			get
			{
				return this._启动;
			}
			set
			{
				if ((this._启动 != value))
				{
					this.On启动Changing(value);
					this.SendPropertyChanging();
					this._启动 = value;
					this.SendPropertyChanged("启动");
					this.On启动Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_退出", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<byte> 退出
		{
			get
			{
				return this._退出;
			}
			set
			{
				if ((this._退出 != value))
				{
					this.On退出Changing(value);
					this.SendPropertyChanging();
					this._退出 = value;
					this.SendPropertyChanged("退出");
					this.On退出Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> 时间
		{
			get
			{
				return this._时间;
			}
			set
			{
				if ((this._时间 != value))
				{
					this.On时间Changing(value);
					this.SendPropertyChanging();
					this._时间 = value;
					this.SendPropertyChanged("时间");
					this.On时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP地址", DbType="NVarChar(20)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string IP地址
		{
			get
			{
				return this._IP地址;
			}
			set
			{
				if ((this._IP地址 != value))
				{
					this.OnIP地址Changing(value);
					this.SendPropertyChanging();
					this._IP地址 = value;
					this.SendPropertyChanged("IP地址");
					this.OnIP地址Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PushPlan")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class PushPlan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _日期;
		
		private System.Nullable<byte> _炉号;
		
		private System.Nullable<System.DateTime> _预定出焦时间;
		
		private System.Nullable<System.DateTime> _实际装煤时间;
		
		private System.Nullable<System.DateTime> _上次装煤时间;
		
		private System.Nullable<short> _计划结焦时间;
		
		private System.Nullable<short> _规定结焦时间;
		
		private System.Nullable<byte> _时段;
		
		private System.Nullable<byte> _班组;
		
		private System.Nullable<System.DateTime> _计划写入时间;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void On日期Changing(System.Nullable<System.DateTime> value);
    partial void On日期Changed();
    partial void On炉号Changing(System.Nullable<byte> value);
    partial void On炉号Changed();
    partial void On预定出焦时间Changing(System.Nullable<System.DateTime> value);
    partial void On预定出焦时间Changed();
    partial void On实际装煤时间Changing(System.Nullable<System.DateTime> value);
    partial void On实际装煤时间Changed();
    partial void On上次装煤时间Changing(System.Nullable<System.DateTime> value);
    partial void On上次装煤时间Changed();
    partial void On计划结焦时间Changing(System.Nullable<short> value);
    partial void On计划结焦时间Changed();
    partial void On规定结焦时间Changing(System.Nullable<short> value);
    partial void On规定结焦时间Changed();
    partial void On时段Changing(System.Nullable<byte> value);
    partial void On时段Changed();
    partial void On班组Changing(System.Nullable<byte> value);
    partial void On班组Changed();
    partial void On计划写入时间Changing(System.Nullable<System.DateTime> value);
    partial void On计划写入时间Changed();
    #endregion
		
		public PushPlan()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_日期", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<System.DateTime> 日期
		{
			get
			{
				return this._日期;
			}
			set
			{
				if ((this._日期 != value))
				{
					this.On日期Changing(value);
					this.SendPropertyChanging();
					this._日期 = value;
					this.SendPropertyChanged("日期");
					this.On日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_炉号", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<byte> 炉号
		{
			get
			{
				return this._炉号;
			}
			set
			{
				if ((this._炉号 != value))
				{
					this.On炉号Changing(value);
					this.SendPropertyChanging();
					this._炉号 = value;
					this.SendPropertyChanged("炉号");
					this.On炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_预定出焦时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<System.DateTime> 预定出焦时间
		{
			get
			{
				return this._预定出焦时间;
			}
			set
			{
				if ((this._预定出焦时间 != value))
				{
					this.On预定出焦时间Changing(value);
					this.SendPropertyChanging();
					this._预定出焦时间 = value;
					this.SendPropertyChanged("预定出焦时间");
					this.On预定出焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实际装煤时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<System.DateTime> 实际装煤时间
		{
			get
			{
				return this._实际装煤时间;
			}
			set
			{
				if ((this._实际装煤时间 != value))
				{
					this.On实际装煤时间Changing(value);
					this.SendPropertyChanging();
					this._实际装煤时间 = value;
					this.SendPropertyChanged("实际装煤时间");
					this.On实际装煤时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_上次装煤时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<System.DateTime> 上次装煤时间
		{
			get
			{
				return this._上次装煤时间;
			}
			set
			{
				if ((this._上次装煤时间 != value))
				{
					this.On上次装煤时间Changing(value);
					this.SendPropertyChanging();
					this._上次装煤时间 = value;
					this.SendPropertyChanged("上次装煤时间");
					this.On上次装煤时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_计划结焦时间", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<short> 计划结焦时间
		{
			get
			{
				return this._计划结焦时间;
			}
			set
			{
				if ((this._计划结焦时间 != value))
				{
					this.On计划结焦时间Changing(value);
					this.SendPropertyChanging();
					this._计划结焦时间 = value;
					this.SendPropertyChanged("计划结焦时间");
					this.On计划结焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_规定结焦时间", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<short> 规定结焦时间
		{
			get
			{
				return this._规定结焦时间;
			}
			set
			{
				if ((this._规定结焦时间 != value))
				{
					this.On规定结焦时间Changing(value);
					this.SendPropertyChanging();
					this._规定结焦时间 = value;
					this.SendPropertyChanged("规定结焦时间");
					this.On规定结焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_时段", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<byte> 时段
		{
			get
			{
				return this._时段;
			}
			set
			{
				if ((this._时段 != value))
				{
					this.On时段Changing(value);
					this.SendPropertyChanging();
					this._时段 = value;
					this.SendPropertyChanged("时段");
					this.On时段Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班组", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<byte> 班组
		{
			get
			{
				return this._班组;
			}
			set
			{
				if ((this._班组 != value))
				{
					this.On班组Changing(value);
					this.SendPropertyChanging();
					this._班组 = value;
					this.SendPropertyChanged("班组");
					this.On班组Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_计划写入时间", DbType="SmallDateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<System.DateTime> 计划写入时间
		{
			get
			{
				return this._计划写入时间;
			}
			set
			{
				if ((this._计划写入时间 != value))
				{
					this.On计划写入时间Changing(value);
					this.SendPropertyChanging();
					this._计划写入时间 = value;
					this.SendPropertyChanged("计划写入时间");
					this.On计划写入时间Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PingInfo")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class PingInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<byte> _预定装煤炉号;
		
		private System.Nullable<System.DateTime> _预定出焦时间;
		
		private System.Nullable<byte> _T实际炉号;
		
		private System.Nullable<byte> _T平煤炉号;
		
		private System.Nullable<byte> _M炉号;
		
		private System.Nullable<int> _T物理地址;
		
		private System.Nullable<int> _M物理地址;
		
		private System.Nullable<int> _Ping联锁信息;
		
		private System.Nullable<System.DateTime> _Begin平煤时间;
		
		private System.Nullable<System.DateTime> _End平煤时间;
		
		private System.Nullable<System.DateTime> _Plan平煤时间;
		
		private System.Nullable<byte> _P时段;
		
		private System.Nullable<byte> _G班组;
		
		private System.Nullable<byte> _Max平煤电流;
		
		private System.Nullable<byte> _Avg平煤电流;
		
		private string _Cur平煤电流;
		
		private string _Pole平煤杆长;
		
		private System.Nullable<int> _PlanIndex;
		
		private System.Nullable<int> _PlanCount;
		
		private System.Nullable<System.DateTime> _BeginTime;
		
		private System.Nullable<System.DateTime> _EndTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void On预定装煤炉号Changing(System.Nullable<byte> value);
    partial void On预定装煤炉号Changed();
    partial void On预定出焦时间Changing(System.Nullable<System.DateTime> value);
    partial void On预定出焦时间Changed();
    partial void OnT实际炉号Changing(System.Nullable<byte> value);
    partial void OnT实际炉号Changed();
    partial void OnT平煤炉号Changing(System.Nullable<byte> value);
    partial void OnT平煤炉号Changed();
    partial void OnM炉号Changing(System.Nullable<byte> value);
    partial void OnM炉号Changed();
    partial void OnT物理地址Changing(System.Nullable<int> value);
    partial void OnT物理地址Changed();
    partial void OnM物理地址Changing(System.Nullable<int> value);
    partial void OnM物理地址Changed();
    partial void OnPing联锁信息Changing(System.Nullable<int> value);
    partial void OnPing联锁信息Changed();
    partial void OnBegin平煤时间Changing(System.Nullable<System.DateTime> value);
    partial void OnBegin平煤时间Changed();
    partial void OnEnd平煤时间Changing(System.Nullable<System.DateTime> value);
    partial void OnEnd平煤时间Changed();
    partial void OnPlan平煤时间Changing(System.Nullable<System.DateTime> value);
    partial void OnPlan平煤时间Changed();
    partial void OnP时段Changing(System.Nullable<byte> value);
    partial void OnP时段Changed();
    partial void OnG班组Changing(System.Nullable<byte> value);
    partial void OnG班组Changed();
    partial void OnMax平煤电流Changing(System.Nullable<byte> value);
    partial void OnMax平煤电流Changed();
    partial void OnAvg平煤电流Changing(System.Nullable<byte> value);
    partial void OnAvg平煤电流Changed();
    partial void OnCur平煤电流Changing(string value);
    partial void OnCur平煤电流Changed();
    partial void OnPole平煤杆长Changing(string value);
    partial void OnPole平煤杆长Changed();
    partial void OnPlanIndexChanging(System.Nullable<int> value);
    partial void OnPlanIndexChanged();
    partial void OnPlanCountChanging(System.Nullable<int> value);
    partial void OnPlanCountChanged();
    partial void OnBeginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnBeginTimeChanged();
    partial void OnEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndTimeChanged();
    #endregion
		
		public PingInfo()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_预定装煤炉号", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<byte> 预定装煤炉号
		{
			get
			{
				return this._预定装煤炉号;
			}
			set
			{
				if ((this._预定装煤炉号 != value))
				{
					this.On预定装煤炉号Changing(value);
					this.SendPropertyChanging();
					this._预定装煤炉号 = value;
					this.SendPropertyChanged("预定装煤炉号");
					this.On预定装煤炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_预定出焦时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<System.DateTime> 预定出焦时间
		{
			get
			{
				return this._预定出焦时间;
			}
			set
			{
				if ((this._预定出焦时间 != value))
				{
					this.On预定出焦时间Changing(value);
					this.SendPropertyChanging();
					this._预定出焦时间 = value;
					this.SendPropertyChanged("预定出焦时间");
					this.On预定出焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T实际炉号", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<byte> T实际炉号
		{
			get
			{
				return this._T实际炉号;
			}
			set
			{
				if ((this._T实际炉号 != value))
				{
					this.OnT实际炉号Changing(value);
					this.SendPropertyChanging();
					this._T实际炉号 = value;
					this.SendPropertyChanged("T实际炉号");
					this.OnT实际炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T平煤炉号", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<byte> T平煤炉号
		{
			get
			{
				return this._T平煤炉号;
			}
			set
			{
				if ((this._T平煤炉号 != value))
				{
					this.OnT平煤炉号Changing(value);
					this.SendPropertyChanging();
					this._T平煤炉号 = value;
					this.SendPropertyChanged("T平煤炉号");
					this.OnT平煤炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M炉号", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<byte> M炉号
		{
			get
			{
				return this._M炉号;
			}
			set
			{
				if ((this._M炉号 != value))
				{
					this.OnM炉号Changing(value);
					this.SendPropertyChanging();
					this._M炉号 = value;
					this.SendPropertyChanged("M炉号");
					this.OnM炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T物理地址", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<int> T物理地址
		{
			get
			{
				return this._T物理地址;
			}
			set
			{
				if ((this._T物理地址 != value))
				{
					this.OnT物理地址Changing(value);
					this.SendPropertyChanging();
					this._T物理地址 = value;
					this.SendPropertyChanged("T物理地址");
					this.OnT物理地址Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M物理地址", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<int> M物理地址
		{
			get
			{
				return this._M物理地址;
			}
			set
			{
				if ((this._M物理地址 != value))
				{
					this.OnM物理地址Changing(value);
					this.SendPropertyChanging();
					this._M物理地址 = value;
					this.SendPropertyChanged("M物理地址");
					this.OnM物理地址Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ping联锁信息", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<int> Ping联锁信息
		{
			get
			{
				return this._Ping联锁信息;
			}
			set
			{
				if ((this._Ping联锁信息 != value))
				{
					this.OnPing联锁信息Changing(value);
					this.SendPropertyChanging();
					this._Ping联锁信息 = value;
					this.SendPropertyChanged("Ping联锁信息");
					this.OnPing联锁信息Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Begin平煤时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<System.DateTime> Begin平煤时间
		{
			get
			{
				return this._Begin平煤时间;
			}
			set
			{
				if ((this._Begin平煤时间 != value))
				{
					this.OnBegin平煤时间Changing(value);
					this.SendPropertyChanging();
					this._Begin平煤时间 = value;
					this.SendPropertyChanged("Begin平煤时间");
					this.OnBegin平煤时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End平煤时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<System.DateTime> End平煤时间
		{
			get
			{
				return this._End平煤时间;
			}
			set
			{
				if ((this._End平煤时间 != value))
				{
					this.OnEnd平煤时间Changing(value);
					this.SendPropertyChanging();
					this._End平煤时间 = value;
					this.SendPropertyChanged("End平煤时间");
					this.OnEnd平煤时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plan平煤时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<System.DateTime> Plan平煤时间
		{
			get
			{
				return this._Plan平煤时间;
			}
			set
			{
				if ((this._Plan平煤时间 != value))
				{
					this.OnPlan平煤时间Changing(value);
					this.SendPropertyChanging();
					this._Plan平煤时间 = value;
					this.SendPropertyChanged("Plan平煤时间");
					this.OnPlan平煤时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P时段", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<byte> P时段
		{
			get
			{
				return this._P时段;
			}
			set
			{
				if ((this._P时段 != value))
				{
					this.OnP时段Changing(value);
					this.SendPropertyChanging();
					this._P时段 = value;
					this.SendPropertyChanged("P时段");
					this.OnP时段Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G班组", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<byte> G班组
		{
			get
			{
				return this._G班组;
			}
			set
			{
				if ((this._G班组 != value))
				{
					this.OnG班组Changing(value);
					this.SendPropertyChanging();
					this._G班组 = value;
					this.SendPropertyChanged("G班组");
					this.OnG班组Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Max平煤电流", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public System.Nullable<byte> Max平煤电流
		{
			get
			{
				return this._Max平煤电流;
			}
			set
			{
				if ((this._Max平煤电流 != value))
				{
					this.OnMax平煤电流Changing(value);
					this.SendPropertyChanging();
					this._Max平煤电流 = value;
					this.SendPropertyChanged("Max平煤电流");
					this.OnMax平煤电流Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avg平煤电流", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public System.Nullable<byte> Avg平煤电流
		{
			get
			{
				return this._Avg平煤电流;
			}
			set
			{
				if ((this._Avg平煤电流 != value))
				{
					this.OnAvg平煤电流Changing(value);
					this.SendPropertyChanging();
					this._Avg平煤电流 = value;
					this.SendPropertyChanged("Avg平煤电流");
					this.OnAvg平煤电流Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cur平煤电流", DbType="VarChar(2000)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public string Cur平煤电流
		{
			get
			{
				return this._Cur平煤电流;
			}
			set
			{
				if ((this._Cur平煤电流 != value))
				{
					this.OnCur平煤电流Changing(value);
					this.SendPropertyChanging();
					this._Cur平煤电流 = value;
					this.SendPropertyChanged("Cur平煤电流");
					this.OnCur平煤电流Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pole平煤杆长", DbType="VarChar(2000)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public string Pole平煤杆长
		{
			get
			{
				return this._Pole平煤杆长;
			}
			set
			{
				if ((this._Pole平煤杆长 != value))
				{
					this.OnPole平煤杆长Changing(value);
					this.SendPropertyChanging();
					this._Pole平煤杆长 = value;
					this.SendPropertyChanged("Pole平煤杆长");
					this.OnPole平煤杆长Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanIndex", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public System.Nullable<int> PlanIndex
		{
			get
			{
				return this._PlanIndex;
			}
			set
			{
				if ((this._PlanIndex != value))
				{
					this.OnPlanIndexChanging(value);
					this.SendPropertyChanging();
					this._PlanIndex = value;
					this.SendPropertyChanged("PlanIndex");
					this.OnPlanIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanCount", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<int> PlanCount
		{
			get
			{
				return this._PlanCount;
			}
			set
			{
				if ((this._PlanCount != value))
				{
					this.OnPlanCountChanging(value);
					this.SendPropertyChanging();
					this._PlanCount = value;
					this.SendPropertyChanged("PlanCount");
					this.OnPlanCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginTime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public System.Nullable<System.DateTime> BeginTime
		{
			get
			{
				return this._BeginTime;
			}
			set
			{
				if ((this._BeginTime != value))
				{
					this.OnBeginTimeChanging(value);
					this.SendPropertyChanging();
					this._BeginTime = value;
					this.SendPropertyChanged("BeginTime");
					this.OnBeginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public System.Nullable<System.DateTime> EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PushInfo")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class PushInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<byte> _计划炉号;
		
		private System.Nullable<byte> _实际炉号;
		
		private System.Nullable<byte> _时段;
		
		private System.Nullable<byte> _班组;
		
		private System.Nullable<byte> _联锁;
		
		private System.Nullable<System.DateTime> _实际推焦时间;
		
		private System.Nullable<System.DateTime> _预定出焦时间;
		
		private System.Nullable<System.DateTime> _上次装煤时间;
		
		private System.Nullable<int> _计划结焦时间;
		
		private System.Nullable<int> _规定结焦时间;
		
		private System.Nullable<int> _实际结焦时间;
		
		private System.Nullable<byte> _Max推焦电流;
		
		private System.Nullable<byte> _Avg推焦电流;
		
		private string _推焦电流;
		
		private string _推焦杆长;
		
		private System.Nullable<int> _Push联锁信息;
		
		private System.Nullable<short> _Push工作车序列;
		
		private System.Nullable<int> _Push对中序列;
		
		private System.Nullable<int> _TAddr;
		
		private System.Nullable<int> _LAddr;
		
		private System.Nullable<int> _XAddr;
		
		private System.Nullable<int> _T炉号;
		
		private System.Nullable<int> _L炉号;
		
		private System.Nullable<int> _X炉号;
		
		private System.Nullable<int> _Push车辆通讯状态;
		
		private System.Nullable<int> _PlanIndex;
		
		private System.Nullable<int> _PlanCount;
		
		private System.Nullable<System.DateTime> _BeginTime;
		
		private System.Nullable<System.DateTime> _EndTime;
		
		private System.Nullable<int> _T1Addr;
		
		private System.Nullable<int> _T2Addr;
		
		private System.Nullable<int> _L1Addr;
		
		private System.Nullable<int> _L2Addr;
		
		private System.Nullable<int> _X1Addr;
		
		private System.Nullable<int> _X2Addr;
		
		private System.Nullable<int> _M1Addr;
		
		private System.Nullable<int> _M2Addr;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void On计划炉号Changing(System.Nullable<byte> value);
    partial void On计划炉号Changed();
    partial void On实际炉号Changing(System.Nullable<byte> value);
    partial void On实际炉号Changed();
    partial void On时段Changing(System.Nullable<byte> value);
    partial void On时段Changed();
    partial void On班组Changing(System.Nullable<byte> value);
    partial void On班组Changed();
    partial void On联锁Changing(System.Nullable<byte> value);
    partial void On联锁Changed();
    partial void On实际推焦时间Changing(System.Nullable<System.DateTime> value);
    partial void On实际推焦时间Changed();
    partial void On预定出焦时间Changing(System.Nullable<System.DateTime> value);
    partial void On预定出焦时间Changed();
    partial void On上次装煤时间Changing(System.Nullable<System.DateTime> value);
    partial void On上次装煤时间Changed();
    partial void On计划结焦时间Changing(System.Nullable<int> value);
    partial void On计划结焦时间Changed();
    partial void On规定结焦时间Changing(System.Nullable<int> value);
    partial void On规定结焦时间Changed();
    partial void On实际结焦时间Changing(System.Nullable<int> value);
    partial void On实际结焦时间Changed();
    partial void OnMax推焦电流Changing(System.Nullable<byte> value);
    partial void OnMax推焦电流Changed();
    partial void OnAvg推焦电流Changing(System.Nullable<byte> value);
    partial void OnAvg推焦电流Changed();
    partial void On推焦电流Changing(string value);
    partial void On推焦电流Changed();
    partial void On推焦杆长Changing(string value);
    partial void On推焦杆长Changed();
    partial void OnPush联锁信息Changing(System.Nullable<int> value);
    partial void OnPush联锁信息Changed();
    partial void OnPush工作车序列Changing(System.Nullable<short> value);
    partial void OnPush工作车序列Changed();
    partial void OnPush对中序列Changing(System.Nullable<int> value);
    partial void OnPush对中序列Changed();
    partial void OnTAddrChanging(System.Nullable<int> value);
    partial void OnTAddrChanged();
    partial void OnLAddrChanging(System.Nullable<int> value);
    partial void OnLAddrChanged();
    partial void OnXAddrChanging(System.Nullable<int> value);
    partial void OnXAddrChanged();
    partial void OnT炉号Changing(System.Nullable<int> value);
    partial void OnT炉号Changed();
    partial void OnL炉号Changing(System.Nullable<int> value);
    partial void OnL炉号Changed();
    partial void OnX炉号Changing(System.Nullable<int> value);
    partial void OnX炉号Changed();
    partial void OnPush车辆通讯状态Changing(System.Nullable<int> value);
    partial void OnPush车辆通讯状态Changed();
    partial void OnPlanIndexChanging(System.Nullable<int> value);
    partial void OnPlanIndexChanged();
    partial void OnPlanCountChanging(System.Nullable<int> value);
    partial void OnPlanCountChanged();
    partial void OnBeginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnBeginTimeChanged();
    partial void OnEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndTimeChanged();
    partial void OnT1AddrChanging(System.Nullable<int> value);
    partial void OnT1AddrChanged();
    partial void OnT2AddrChanging(System.Nullable<int> value);
    partial void OnT2AddrChanged();
    partial void OnL1AddrChanging(System.Nullable<int> value);
    partial void OnL1AddrChanged();
    partial void OnL2AddrChanging(System.Nullable<int> value);
    partial void OnL2AddrChanged();
    partial void OnX1AddrChanging(System.Nullable<int> value);
    partial void OnX1AddrChanged();
    partial void OnX2AddrChanging(System.Nullable<int> value);
    partial void OnX2AddrChanged();
    partial void OnM1AddrChanging(System.Nullable<int> value);
    partial void OnM1AddrChanged();
    partial void OnM2AddrChanging(System.Nullable<int> value);
    partial void OnM2AddrChanged();
    #endregion
		
		public PushInfo()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_计划炉号", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public System.Nullable<byte> 计划炉号
		{
			get
			{
				return this._计划炉号;
			}
			set
			{
				if ((this._计划炉号 != value))
				{
					this.On计划炉号Changing(value);
					this.SendPropertyChanging();
					this._计划炉号 = value;
					this.SendPropertyChanged("计划炉号");
					this.On计划炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实际炉号", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public System.Nullable<byte> 实际炉号
		{
			get
			{
				return this._实际炉号;
			}
			set
			{
				if ((this._实际炉号 != value))
				{
					this.On实际炉号Changing(value);
					this.SendPropertyChanging();
					this._实际炉号 = value;
					this.SendPropertyChanged("实际炉号");
					this.On实际炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_时段", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public System.Nullable<byte> 时段
		{
			get
			{
				return this._时段;
			}
			set
			{
				if ((this._时段 != value))
				{
					this.On时段Changing(value);
					this.SendPropertyChanging();
					this._时段 = value;
					this.SendPropertyChanged("时段");
					this.On时段Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班组", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public System.Nullable<byte> 班组
		{
			get
			{
				return this._班组;
			}
			set
			{
				if ((this._班组 != value))
				{
					this.On班组Changing(value);
					this.SendPropertyChanging();
					this._班组 = value;
					this.SendPropertyChanged("班组");
					this.On班组Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_联锁", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public System.Nullable<byte> 联锁
		{
			get
			{
				return this._联锁;
			}
			set
			{
				if ((this._联锁 != value))
				{
					this.On联锁Changing(value);
					this.SendPropertyChanging();
					this._联锁 = value;
					this.SendPropertyChanged("联锁");
					this.On联锁Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实际推焦时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.Nullable<System.DateTime> 实际推焦时间
		{
			get
			{
				return this._实际推焦时间;
			}
			set
			{
				if ((this._实际推焦时间 != value))
				{
					this.On实际推焦时间Changing(value);
					this.SendPropertyChanging();
					this._实际推焦时间 = value;
					this.SendPropertyChanged("实际推焦时间");
					this.On实际推焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_预定出焦时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public System.Nullable<System.DateTime> 预定出焦时间
		{
			get
			{
				return this._预定出焦时间;
			}
			set
			{
				if ((this._预定出焦时间 != value))
				{
					this.On预定出焦时间Changing(value);
					this.SendPropertyChanging();
					this._预定出焦时间 = value;
					this.SendPropertyChanged("预定出焦时间");
					this.On预定出焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_上次装煤时间", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public System.Nullable<System.DateTime> 上次装煤时间
		{
			get
			{
				return this._上次装煤时间;
			}
			set
			{
				if ((this._上次装煤时间 != value))
				{
					this.On上次装煤时间Changing(value);
					this.SendPropertyChanging();
					this._上次装煤时间 = value;
					this.SendPropertyChanged("上次装煤时间");
					this.On上次装煤时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_计划结焦时间", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public System.Nullable<int> 计划结焦时间
		{
			get
			{
				return this._计划结焦时间;
			}
			set
			{
				if ((this._计划结焦时间 != value))
				{
					this.On计划结焦时间Changing(value);
					this.SendPropertyChanging();
					this._计划结焦时间 = value;
					this.SendPropertyChanged("计划结焦时间");
					this.On计划结焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_规定结焦时间", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public System.Nullable<int> 规定结焦时间
		{
			get
			{
				return this._规定结焦时间;
			}
			set
			{
				if ((this._规定结焦时间 != value))
				{
					this.On规定结焦时间Changing(value);
					this.SendPropertyChanging();
					this._规定结焦时间 = value;
					this.SendPropertyChanged("规定结焦时间");
					this.On规定结焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_实际结焦时间", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public System.Nullable<int> 实际结焦时间
		{
			get
			{
				return this._实际结焦时间;
			}
			set
			{
				if ((this._实际结焦时间 != value))
				{
					this.On实际结焦时间Changing(value);
					this.SendPropertyChanging();
					this._实际结焦时间 = value;
					this.SendPropertyChanged("实际结焦时间");
					this.On实际结焦时间Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Max推焦电流", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public System.Nullable<byte> Max推焦电流
		{
			get
			{
				return this._Max推焦电流;
			}
			set
			{
				if ((this._Max推焦电流 != value))
				{
					this.OnMax推焦电流Changing(value);
					this.SendPropertyChanging();
					this._Max推焦电流 = value;
					this.SendPropertyChanged("Max推焦电流");
					this.OnMax推焦电流Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avg推焦电流", DbType="TinyInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public System.Nullable<byte> Avg推焦电流
		{
			get
			{
				return this._Avg推焦电流;
			}
			set
			{
				if ((this._Avg推焦电流 != value))
				{
					this.OnAvg推焦电流Changing(value);
					this.SendPropertyChanging();
					this._Avg推焦电流 = value;
					this.SendPropertyChanged("Avg推焦电流");
					this.OnAvg推焦电流Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_推焦电流", DbType="VarChar(2000)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public string 推焦电流
		{
			get
			{
				return this._推焦电流;
			}
			set
			{
				if ((this._推焦电流 != value))
				{
					this.On推焦电流Changing(value);
					this.SendPropertyChanging();
					this._推焦电流 = value;
					this.SendPropertyChanged("推焦电流");
					this.On推焦电流Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_推焦杆长", DbType="VarChar(2000)")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public string 推焦杆长
		{
			get
			{
				return this._推焦杆长;
			}
			set
			{
				if ((this._推焦杆长 != value))
				{
					this.On推焦杆长Changing(value);
					this.SendPropertyChanging();
					this._推焦杆长 = value;
					this.SendPropertyChanged("推焦杆长");
					this.On推焦杆长Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Push联锁信息", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public System.Nullable<int> Push联锁信息
		{
			get
			{
				return this._Push联锁信息;
			}
			set
			{
				if ((this._Push联锁信息 != value))
				{
					this.OnPush联锁信息Changing(value);
					this.SendPropertyChanging();
					this._Push联锁信息 = value;
					this.SendPropertyChanged("Push联锁信息");
					this.OnPush联锁信息Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Push工作车序列", DbType="SmallInt")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public System.Nullable<short> Push工作车序列
		{
			get
			{
				return this._Push工作车序列;
			}
			set
			{
				if ((this._Push工作车序列 != value))
				{
					this.OnPush工作车序列Changing(value);
					this.SendPropertyChanging();
					this._Push工作车序列 = value;
					this.SendPropertyChanged("Push工作车序列");
					this.OnPush工作车序列Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Push对中序列", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public System.Nullable<int> Push对中序列
		{
			get
			{
				return this._Push对中序列;
			}
			set
			{
				if ((this._Push对中序列 != value))
				{
					this.OnPush对中序列Changing(value);
					this.SendPropertyChanging();
					this._Push对中序列 = value;
					this.SendPropertyChanged("Push对中序列");
					this.OnPush对中序列Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAddr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public System.Nullable<int> TAddr
		{
			get
			{
				return this._TAddr;
			}
			set
			{
				if ((this._TAddr != value))
				{
					this.OnTAddrChanging(value);
					this.SendPropertyChanging();
					this._TAddr = value;
					this.SendPropertyChanged("TAddr");
					this.OnTAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAddr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public System.Nullable<int> LAddr
		{
			get
			{
				return this._LAddr;
			}
			set
			{
				if ((this._LAddr != value))
				{
					this.OnLAddrChanging(value);
					this.SendPropertyChanging();
					this._LAddr = value;
					this.SendPropertyChanged("LAddr");
					this.OnLAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XAddr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public System.Nullable<int> XAddr
		{
			get
			{
				return this._XAddr;
			}
			set
			{
				if ((this._XAddr != value))
				{
					this.OnXAddrChanging(value);
					this.SendPropertyChanging();
					this._XAddr = value;
					this.SendPropertyChanged("XAddr");
					this.OnXAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T炉号", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=23)]
		public System.Nullable<int> T炉号
		{
			get
			{
				return this._T炉号;
			}
			set
			{
				if ((this._T炉号 != value))
				{
					this.OnT炉号Changing(value);
					this.SendPropertyChanging();
					this._T炉号 = value;
					this.SendPropertyChanged("T炉号");
					this.OnT炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L炉号", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=24)]
		public System.Nullable<int> L炉号
		{
			get
			{
				return this._L炉号;
			}
			set
			{
				if ((this._L炉号 != value))
				{
					this.OnL炉号Changing(value);
					this.SendPropertyChanging();
					this._L炉号 = value;
					this.SendPropertyChanged("L炉号");
					this.OnL炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X炉号", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=25)]
		public System.Nullable<int> X炉号
		{
			get
			{
				return this._X炉号;
			}
			set
			{
				if ((this._X炉号 != value))
				{
					this.OnX炉号Changing(value);
					this.SendPropertyChanging();
					this._X炉号 = value;
					this.SendPropertyChanged("X炉号");
					this.OnX炉号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Push车辆通讯状态", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=26)]
		public System.Nullable<int> Push车辆通讯状态
		{
			get
			{
				return this._Push车辆通讯状态;
			}
			set
			{
				if ((this._Push车辆通讯状态 != value))
				{
					this.OnPush车辆通讯状态Changing(value);
					this.SendPropertyChanging();
					this._Push车辆通讯状态 = value;
					this.SendPropertyChanged("Push车辆通讯状态");
					this.OnPush车辆通讯状态Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanIndex", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=27)]
		public System.Nullable<int> PlanIndex
		{
			get
			{
				return this._PlanIndex;
			}
			set
			{
				if ((this._PlanIndex != value))
				{
					this.OnPlanIndexChanging(value);
					this.SendPropertyChanging();
					this._PlanIndex = value;
					this.SendPropertyChanged("PlanIndex");
					this.OnPlanIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanCount", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=28)]
		public System.Nullable<int> PlanCount
		{
			get
			{
				return this._PlanCount;
			}
			set
			{
				if ((this._PlanCount != value))
				{
					this.OnPlanCountChanging(value);
					this.SendPropertyChanging();
					this._PlanCount = value;
					this.SendPropertyChanged("PlanCount");
					this.OnPlanCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginTime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=29)]
		public System.Nullable<System.DateTime> BeginTime
		{
			get
			{
				return this._BeginTime;
			}
			set
			{
				if ((this._BeginTime != value))
				{
					this.OnBeginTimeChanging(value);
					this.SendPropertyChanging();
					this._BeginTime = value;
					this.SendPropertyChanged("BeginTime");
					this.OnBeginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=30)]
		public System.Nullable<System.DateTime> EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T1Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=31)]
		public System.Nullable<int> T1Addr
		{
			get
			{
				return this._T1Addr;
			}
			set
			{
				if ((this._T1Addr != value))
				{
					this.OnT1AddrChanging(value);
					this.SendPropertyChanging();
					this._T1Addr = value;
					this.SendPropertyChanged("T1Addr");
					this.OnT1AddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T2Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=32)]
		public System.Nullable<int> T2Addr
		{
			get
			{
				return this._T2Addr;
			}
			set
			{
				if ((this._T2Addr != value))
				{
					this.OnT2AddrChanging(value);
					this.SendPropertyChanging();
					this._T2Addr = value;
					this.SendPropertyChanged("T2Addr");
					this.OnT2AddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L1Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=33)]
		public System.Nullable<int> L1Addr
		{
			get
			{
				return this._L1Addr;
			}
			set
			{
				if ((this._L1Addr != value))
				{
					this.OnL1AddrChanging(value);
					this.SendPropertyChanging();
					this._L1Addr = value;
					this.SendPropertyChanged("L1Addr");
					this.OnL1AddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L2Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=34)]
		public System.Nullable<int> L2Addr
		{
			get
			{
				return this._L2Addr;
			}
			set
			{
				if ((this._L2Addr != value))
				{
					this.OnL2AddrChanging(value);
					this.SendPropertyChanging();
					this._L2Addr = value;
					this.SendPropertyChanged("L2Addr");
					this.OnL2AddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X1Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=35)]
		public System.Nullable<int> X1Addr
		{
			get
			{
				return this._X1Addr;
			}
			set
			{
				if ((this._X1Addr != value))
				{
					this.OnX1AddrChanging(value);
					this.SendPropertyChanging();
					this._X1Addr = value;
					this.SendPropertyChanged("X1Addr");
					this.OnX1AddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X2Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=36)]
		public System.Nullable<int> X2Addr
		{
			get
			{
				return this._X2Addr;
			}
			set
			{
				if ((this._X2Addr != value))
				{
					this.OnX2AddrChanging(value);
					this.SendPropertyChanging();
					this._X2Addr = value;
					this.SendPropertyChanged("X2Addr");
					this.OnX2AddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M1Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=37)]
		public System.Nullable<int> M1Addr
		{
			get
			{
				return this._M1Addr;
			}
			set
			{
				if ((this._M1Addr != value))
				{
					this.OnM1AddrChanging(value);
					this.SendPropertyChanging();
					this._M1Addr = value;
					this.SendPropertyChanged("M1Addr");
					this.OnM1AddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M2Addr", DbType="Int")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=38)]
		public System.Nullable<int> M2Addr
		{
			get
			{
				return this._M2Addr;
			}
			set
			{
				if ((this._M2Addr != value))
				{
					this.OnM2AddrChanging(value);
					this.SendPropertyChanging();
					this._M2Addr = value;
					this.SendPropertyChanged("M2Addr");
					this.OnM2AddrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
